version: '3.7'

services:
  treetime-dev-reverse-proxy:
    container_name: treetime-dev-reverse-proxy
    image: treetime-dev-reverse-proxy
    build:
      context: ./
      dockerfile: ../reverse-proxy/development/Dockerfile
    command: sh /etc/nginx/nginx-watch.sh
    volumes:
      - ../reverse-proxy/development/etc/nginx:/etc/nginx:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 44443:44443
      - 8080:8080
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    depends_on:
      - treetime-dev-api
      - treetime-dev-web
    restart: 'no'
    init: true
    tty: true

  treetime-dev-api:
    depends_on:
      - treetime-dev-taskqueue
    container_name: treetime-dev-api
    image: treetime-dev-api
    build:
      context: ./
      dockerfile: node-git-alpine/Dockerfile
    command: sh -c "cd /code/api && yarn install && dockerize -wait tcp://treetime-dev-taskqueue:5672 -timeout 60s >/dev/null && yarn dev"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-web:
    depends_on:
      - treetime-dev-api
    container_name: treetime-dev-web
    image: treetime-dev-web
    build:
      context: ./
      dockerfile: node-git-alpine/Dockerfile
    command: sh -c "cd /code/web && yarn install && yarn dev"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-worker:
    depends_on:
      - treetime-dev-taskqueue
    container_name: treetime-dev-worker
    image: treetime-dev-worker
    build:
      context: ../
      dockerfile: worker/Dockerfile
    command: sh -c "mkdir -p /code/worker/output && cd /code/worker/output && dockerize -wait tcp://treetime-dev-taskqueue:5672 -timeout 60s >/dev/null && python3 ../src/tree_time_process.py"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-taskqueue:
    container_name: treetime-dev-taskqueue
    image: rabbitmq:3.8.2-management-alpine
    volumes:
      - ../taskqueue/etc/rabbitmq:/etc/rabbitmq:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ../.env
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    tty: true
